Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.synced_folder "scripts/", "/home/vagrant/scripts"
  config.vm.synced_folder "data/", "/home/vagrant/vdata"
  config.vm.define "master" do |mch1|
    mch1.vm.network "private_network", ip: "10.5.5.200"
  end

  config.vm.define "slave" do |mch2|
    mch2.vm.network "private_network", ip: "10.5.5.201"
  end
end

